version: '3'
services:
  app:
    image: "tcpipuk/chatgpt-memory:latest"
    env_file:
      - ".env"
  redis:
    container_name: ${REDIS_HOST}
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
