[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[install]
script = "pip install --prefer-binary"

[tool.poetry.virtualenvs]
create = false
